name: CI/CD

on: push

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the current version
        id: version
        run: echo "version=$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.version }}
          name: "Release v${{ env.version }}"
          body: Test
          token: ${{ secrets.GITHUB_TOKEN }}